spring:
  profiles:
    active: dev
  application:
    name: wrtnrd-backend
  datasource:
    url: {{ JDBC_URL }}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
logging:
  level:
    org.springframework.security: trace
    root: debug
jwt:
  secret-key: {{ JWT_SECRET_KEY}}
  access-token:
    expiration: 1800000 # 30minutes
  refresh-token:
    expiration: 7200000 # 2 hours
