spring:
  application:
    name: wrtnrd-backend
  datasource:
    url: ${JDBC_URL}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
logging:
  level:
    org.springframework.security: info
    root: info
jwt:
  secret-key: ${JWT_SECRET_KEY}
app:
  frontend-url: ${FRONTEND_URL}
server:
  port: 8000